global-variables:
  environment: &default_environment
    FLASK_ENV: "development"
    FLASK_APP: "./src/api/__init__.py"
    DATASET_DIR: "./src/files"
    CURRENT_MODEL_DIR: "./src/current_model"
    TRAINED_MODELS_DIR: "./src/trained_models"
    FEATURE_DEFINITION_PATH: "./src/files/features-definition.json"
    LOGS_DIRECTORY: "./src/api_logs"


kind: pipeline
type: docker
name: mushroom-classification-flask-api-pipeline

steps: 
- name: build-and-test
  environment:
    <<: *default_environment
  image: python:3.7.5-slim-buster
  commands:
    - pip install -r src/requirements.txt
    - coverage run -m py.test
    - pylint --rcfile src/.pylintrc --exit-zero --output-format=parseable --reports=no src/api src/mushroom_classifier src/test_api src/test_mushroom_classifier

- name: publish-docker-image  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhubusername
    password:
      from_secret: dockerhubpassword
    repo:
      from_secret: dockerhubimage
    dockerfile: ./src/dockerfile
  auto_tag: true
  when:
    branch:
    - master