version: '3.8'

services:
  web:
    build: ./src
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./src/:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.docker.env
    environment:
      - FLASK_ENV=development
