version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  error:
    class: logging.FileHandler
    level: ERROR
    formatter: simple
    filename: ./logs/error.log
    encoding: utf8
loggers:
  error_logger:
    level: ERROR
    handlers: [error]
    propagate: no
root:
  level: DEBUG
  handlers: [console]